name: Simple WordPress and MySQL Setup with Docker

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (optional)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker

      # Step 3: Set up WordPress and MySQL containers
      - name: Start WordPress and MySQL using Docker
        run: |
          # Start MySQL container
          docker run --name mysql -e MYSQL_ROOT_PASSWORD=root_password -e MYSQL_DATABASE=wordpress -d mysql:8.0

          # Start WordPress container
          docker run --name wordpress --link mysql:mysql -p 8080:80 -e WORDPRESS_DB_HOST=mysql:3306 -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=root_password -d wordpress

      # Step 4: Wait for WordPress to be ready
      - name: Wait for WordPress to be ready
        run: |
          echo "Waiting for WordPress to start..."
          for i in {1..10}; do
            if curl --fail http://localhost:8080 | grep -q "WordPress"; then
              echo "WordPress is ready!"
              exit 0
            else
              echo "Retrying WordPress setup..."
              sleep 10
            fi
          done
          echo "WordPress setup failed!" && exit 1

      # Step 5: Generate a Report for WordPress Database
      - name: Generate Report for WordPress Database
        run: |
          # Show the MySQL databases and generate a simple report
          docker exec mysql mysql -u root -proot_password -e "SHOW DATABASES;" > report.txt
          docker exec mysql mysql -u root -proot_password -e "SELECT * FROM wordpress.wp_users LIMIT 5;" >> report.txt

      # Step 6: Upload the Report as Artifact
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-report
          path: report.txt
