name: WordPress Docker Setup with MySQL

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Docker Buildx (Optional, helpful for Docker actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

     # Step 4: Start the containers using Docker Compose
      - name: Start WordPress and MySQL containers
        run: |
          docker-compose up -d

      # Step 5: Wait for WordPress to become available
      - name: Wait for WordPress to be available
        run: |
          echo "Waiting for WordPress to be ready..."
          sleep 60  # Wait for 60 seconds for WordPress to initialize

      # Step 6: Check if WordPress is running
      - name: Check if WordPress is running
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:80)
          echo "WordPress is up and running!"

      # Step 7: Clean up Docker containers
      - name: Clean up Docker containers
        run: |
          docker-compose down
